baseURL: "https://georgemunyoro.me"
title: George Munyoro
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
menu:
    main:
        - name: Blog 
          url: blog/
          weight: 1
        - name: About
          url: about/
          weight: 3
        - name: Portfolio
          url: portfolio/
          weight: 2
params:
    profileMode:
        enabled: true
        title: "Fullstack Web Developer" # optional default will be site title
        imageUrl: "https://www.pngitem.com/pimgs/m/464-4644556_full-stack-icon-png-transparent-png.png" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Blog
              url: "/blog"
            - name: Github
              url: "https://github.com/georgemunyoro"

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/georgemunyoro"
        - name: "twitter"
          url: "https://twitter.com/george_munyoro"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/georgemunyoro"
        - name: "stackoverflow"
          url: "https://stackoverflow.com/users/11886597/george-munyoro"
